title: Rick Mata # your name (or website title) here
logo: "1672266764118.jfif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science 
  Writer. Minimalist. Mindfullness  <br><br>
  <a href="https://www.linkedin.com/in/rick-mata-jr/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
